In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.backends.mps.is_built())
print(torch.backends.mps.is_available())

2.3.1
True
True


# Introduction to Tensors

## Creating Tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [9]:
# Get the tensor back as a Python int
scalar.item()

7

In [7]:
scalar.dtype

torch.int64

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

In [20]:
matrix[1][1]

tensor(10)

In [21]:
# Tensor
tensor = torch.tensor([
    [
        [1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]
    ]
])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
tensor.ndim

3

In [23]:
tensor.shape

torch.Size([1, 3, 3])

In [25]:
tensor[0][1][1]

tensor(6)

### Rendom tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors with full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
# Create a random tensor of shape (3, 4)

In [33]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [34]:
random_tensor.ndim

2

In [37]:
# Create a random tensor with similar shape to an image tensor.
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [40]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [53]:
# Use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [64]:
float_32_tensor = torch.tensor([3., 6., 9.], 
                               dtype=None, # What datatype is the tensor, torch.float32, torch.float16
                               device=None, # Where does the tensor reside, CPU or GPU 
                               requires_grad=False) # Whether or not to track the gradient
float_32_tensor

tensor([3., 6., 9.])

In [65]:
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

In [79]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [80]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype use `.dtype`
2. Tensors not right shape - to get shape use `.shape`
3. Tensors not on the right device - to get device use `.device`

In [82]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2524, 0.3103, 0.1673, 0.8201],
        [0.9205, 0.2719, 0.2012, 0.1478],
        [0.3702, 0.1441, 0.1284, 0.2582]])

In [83]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.2524, 0.3103, 0.1673, 0.8201],
        [0.9205, 0.2719, 0.2012, 0.1478],
        [0.3702, 0.1441, 0.1284, 0.2582]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [85]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [86]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [87]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [88]:
# Try out pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [89]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Eleemnt-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match: shape):
* `(3, 2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3)` will work
* `(2, 3) @ (3, 2)` will work

With inner dimensions we mean the dimensions as specified by the right and left most value of the shape:

* `(x, 2) @ (2, x)` will work
* `(x, 3) @ (3, x)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` resulting shape will be `(2, 2)`
* `(3, 2) @ (2, 3)` resulting shape will be `(3, 3)`

In [93]:
# Element wise multiplication
print (tensor, '*', tensor)
print(f'Equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [96]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [114]:
tensor @ tensor

tensor(14)

In [97]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [112]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.02 ms, sys: 466 μs, total: 1.49 ms
Wall time: 1.11 ms


tensor(14)

In [113]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 113 μs, sys: 4 μs, total: 117 μs
Wall time: 122 μs


tensor(14)

In [108]:
range(len(tensor))

range(0, 3)

### One of the most common errors in deep lering: shape errors

In [116]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [119]:
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

# Resutls the following error:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of the given tensor.

In [125]:
print(f'Transposed: \n {tensor_B.T}')
print(f'Original: \n {tensor_B}')


Transposed: 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])
Original: 
 tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [126]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregation)

In [128]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [129]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [131]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [133]:
# Find the mean
# torch.mean(x), x.mean()

# Results in:
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [134]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [135]:
x.type(torch.float32).mean()

tensor(45.)

In [136]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max 

In [140]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where hte minimum value occurs. 
x.argmin()

tensor(0)

In [139]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [157]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [159]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [161]:
# Change the view
z = x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [162]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [172]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [178]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [180]:
# torch.unsqueeze() - adds a single diemnsion to a target tensor at a specified dimension 
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [182]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
# returns a view
x_original = torch.rand(size=(224, 224, 3)) # h, w, c

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}') # [w, h, c]
print(f'New shape: {x_permuted.shape}') # [c, w, h}

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [183]:
x_original[0,0,0] = 728218
x_original[0, 0, 0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [186]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [187]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])